version: "3.2"

services:
  phonebook:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    image: a3s/phonebook
    container_name: phonebook
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - quarkus

  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: R3c1f3!
      MYSQL_DATABASE: phonebook
      MYSQL_USER: root
      MYSQL_PASSWORD: R3c1f3!
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - quarkus

networks:
  quarkus: