/**
 * phonebook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { People } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PeopleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete People by id
     * Delete People by id
     * @param body 
     */
    apiPeopleDelete(body?: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Get all People
     * Get all People
     * @param page The page number
     * @param size The size of page
     * @param sortcolumn The sort column
     */
    apiPeopleGet(page?: number, size?: number, sortcolumn?: Array<string>, extraHttpRequestParams?: any): Observable<Array<People>>;

    /**
     * Get People by id
     * Get People by id
     * @param id The People id
     */
    apiPeopleIdGet(id: number, extraHttpRequestParams?: any): Observable<People>;

    /**
     * Update People by id
     * Update People by id
     * @param id The People id
     */
    apiPeopleIdPut(id: number, extraHttpRequestParams?: any): Observable<People>;

    /**
     * Create People
     * Create People
     * @param people 
     */
    apiPeoplePost(people?: People, extraHttpRequestParams?: any): Observable<People>;

}
