/**
 * phonebook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all User
     * Get all User
     * @param page The page number
     * @param size The size of page
     * @param sortcolumn The sort column
     */
    userGet(page?: number, size?: number, sortcolumn?: Array<string>, extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * Delete User by id
     * Delete User by id
     * @param id The User id
     */
    userIdDelete(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Get User by id
     * Get User by id
     * @param id The User id
     */
    userIdGet(id: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Update User by id
     * Update User by id
     * @param id The User id
     */
    userIdPut(id: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Create User
     * Create User
     * @param user 
     */
    userPost(user?: User, extraHttpRequestParams?: any): Observable<User>;

}
